import { InlineMessage } from '../..'
import DemoWrapper from '../../UI/DemoWrapper'

const InlineMessageDemo = () => (
  <DemoWrapper title='Inline Message'>
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '8px',
      }}
    >
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-white'
        actionLabel='Label'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-white'
        actionLabel='Label'
        isButtonRight
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-white'
        actionLabel='Label'
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-white'
        actionLabel='Label'
        isButtonRight
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-grey'
        actionLabel='Label'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-grey'
        actionLabel='Label'
        isButtonRight
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-grey'
        actionLabel='Label'
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='info-grey'
        actionLabel='Label'
        isButtonRight
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='success'
        actionLabel='Label'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='success'
        actionLabel='Label'
        isButtonRight
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='success'
        actionLabel='Label'
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='success'
        actionLabel='Label'
        isButtonRight
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='warning'
        actionLabel='Label'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='warning'
        actionLabel='Label'
        isButtonRight
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='warning'
        actionLabel='Label'
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='warning'
        actionLabel='Label'
        isButtonRight
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='error'
        actionLabel='Label'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='error'
        actionLabel='Label'
        isButtonRight
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='error'
        actionLabel='Label'
        size='small'
      />
      <InlineMessage
        label='Label'
        caption='caption'
        variant='error'
        actionLabel='Label'
        isButtonRight
        size='small'
      />
    </div>
  </DemoWrapper>
)

export default InlineMessageDemo
