#!/usr/bin/env node
// agents/setup-ai.mjs — WRI Design System AI Setup
// Distributes AGENTS.md to the correct location for each detected IDE.
// Usage: npx ds setup-ai

import {
  existsSync,
  mkdirSync,
  copyFileSync,
  writeFileSync,
  readFileSync,
  readdirSync,
  cpSync,
} from 'fs'
import { join, dirname, relative, resolve } from 'path'
import { execSync } from 'child_process'
import { homedir } from 'os'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SOURCE = join(__dirname, 'AGENTS.md')
const SOURCE_COMPONENT_INSTRUCTIONS = join(__dirname, 'wri-ds.instructions.md')
// Where we write the setup files.
// Default is the repo root you're currently in when you run the CLI.
// You can optionally pass a target directory as argv[2].
const ROOT = resolve(process.argv[2] ?? process.cwd())
const HOME = homedir()

const installed = []
const skipped = []

console.log('\nWRI Design System — AI Setup')
console.log('==============================')

if (!existsSync(SOURCE)) {
  console.error('❌  AGENTS.md not found at', SOURCE)
  process.exit(1)
}

// ── Helpers ──────────────────────────────────────────────────────

function installFile(dest, label, src = SOURCE) {
  mkdirSync(dirname(dest), { recursive: true })
  copyFileSync(src, dest)
  installed.push(`${label} → ${relative(ROOT, dest)}`)
}

function commandExists(cmd) {
  try {
    execSync(`command -v ${cmd}`, { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

function pathExists(...parts) {
  return existsSync(join(...parts))
}

function dirContains(dir, substring) {
  try {
    return readdirSync(dir).some((f) => f.includes(substring))
  } catch {
    return false
  }
}

function writeJSON(dest, label, content) {
  if (existsSync(dest)) {
    skipped.push(`${label} (already exists — skipped to avoid overwrite)`)
    return
  }
  mkdirSync(dirname(dest), { recursive: true })
  writeFileSync(dest, JSON.stringify(content, null, 2) + '\n')
  installed.push(`${label} → ${relative(ROOT, dest)}`)
}

function installSkill(skillName) {
  const srcDir = join(__dirname, 'skills', skillName)
  if (!existsSync(srcDir)) {
    skipped.push(`Skill ${skillName} (source not found)`)
    return
  }

  // Install for Gemini/Antigravity
  const destGeminiDir = join(ROOT, '.gemini', 'skills', skillName)
  mkdirSync(destGeminiDir, { recursive: true })
  cpSync(srcDir, destGeminiDir, { recursive: true })
  installed.push(
    `Gemini Skill: ${skillName} → ${relative(ROOT, destGeminiDir)}`,
  )

  // Install for Claude
  const destClaudeDir = join(ROOT, '.claude', 'skills', skillName)
  mkdirSync(destClaudeDir, { recursive: true })
  cpSync(srcDir, destClaudeDir, { recursive: true })
  installed.push(
    `Claude Skill: ${skillName} → ${relative(ROOT, destClaudeDir)}`,
  )
}

function ensureGitignoreBlock() {
  const gitignorePath = join(ROOT, '.gitignore')
  const marker =
    '# AI setup — generated by agents/setup-ai.js (npx ds setup-ai)'
  const blockLines = [
    marker,
    '.windsurfrules',
    '.clinerules',
    '.github/copilot-instructions.md',
    '.github/instructions/wri-ds.instructions.md',
    '.cursor/rules',
    '.cursor/mcp.json',
    '.vscode/mcp.json',
  ]
  const block = blockLines.join('\n') + '\n'

  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, block)
    installed.push('.gitignore → .gitignore')
    return
  }

  const current = readFileSync(gitignorePath, 'utf8')
  if (current.includes(marker)) {
    skipped.push('.gitignore (block already present)')
    return
  }

  const prefix = current.endsWith('\n') ? '\n' : '\n\n'
  writeFileSync(gitignorePath, current + prefix + block)
  installed.push('.gitignore → .gitignore (appended)')
}

// ── MCP config objects ────────────────────────────────────────────

const MCP_STORYBOOK_URL = 'https://wri.github.io/wri-design-systems/index.json'

const mcpCursor = {
  mcpServers: {
    figma: {
      url: 'https://mcp.figma.com/mcp',
      type: 'http',
    },
    'wri-storybook': {
      command: 'npx',
      args: ['-y', 'storybook-mcp@latest'],
      env: { STORYBOOK_URL: MCP_STORYBOOK_URL },
    },
    'chakra-ui': {
      command: 'npx',
      args: ['-y', '@chakra-ui/react-mcp'],
    },
  },
}

const mcpVSCode = {
  servers: {
    figma: {
      type: 'http',
      url: 'https://mcp.figma.com/mcp',
    },
    'wri-storybook': {
      type: 'stdio',
      command: 'npx',
      args: ['-y', 'storybook-mcp@latest'],
      env: { STORYBOOK_URL: MCP_STORYBOOK_URL },
    },
    'chakra-ui': {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@chakra-ui/react-mcp'],
    },
  },
}

// Cursor
const hasCursor =
  pathExists(HOME, '.cursor') ||
  pathExists('/Applications/Cursor.app') ||
  commandExists('cursor')

if (hasCursor) {
  installFile(join(ROOT, '.cursor', 'rules'), 'Cursor (rules)')
  writeJSON(join(ROOT, '.cursor', 'mcp.json'), 'Cursor MCP config', mcpCursor)
} else {
  skipped.push('Cursor (not detected)')
}

// GitHub Copilot / VS Code
const hasVSCode =
  commandExists('code') ||
  pathExists(HOME, '.vscode') ||
  pathExists('/Applications/Visual Studio Code.app')

if (hasVSCode) {
  installFile(
    join(ROOT, '.github', 'copilot-instructions.md'),
    'GitHub Copilot',
  )
  if (existsSync(SOURCE_COMPONENT_INSTRUCTIONS)) {
    installFile(
      join(ROOT, '.github', 'instructions', 'wri-ds.instructions.md'),
      'GitHub Copilot (component instructions)',
      SOURCE_COMPONENT_INSTRUCTIONS,
    )
  }
  writeJSON(join(ROOT, '.vscode', 'mcp.json'), 'VS Code MCP config', mcpVSCode)
} else {
  skipped.push('GitHub Copilot / VS Code (not detected)')
}

// Windsurf
const hasWindsurf =
  pathExists(HOME, '.codeium') ||
  pathExists('/Applications/Windsurf.app') ||
  commandExists('windsurf')

if (hasWindsurf) {
  installFile(join(ROOT, '.windsurfrules'), 'Windsurf')
} else {
  skipped.push('Windsurf (not detected)')
}

// Cline (VS Code extension)
const hasCline = dirContains(join(HOME, '.vscode', 'extensions'), 'cline')

if (hasCline) {
  installFile(join(ROOT, '.clinerules'), 'Cline')
} else {
  skipped.push('Cline (not detected)')
}

// Skills
installSkill('ds-ui-creator')

ensureGitignoreBlock()

// ── Summary ───────────────────────────────────────────────────────

console.log('\n✅ Installed:')
installed.forEach((item) => console.log('  ', item))

if (skipped.length) {
  console.log('\n⏭  Skipped:')
  skipped.forEach((item) => console.log('  ', item))
}

console.log('\nDone. Your AI tools now have full WRI Design System context.')
console.log('Storybook: https://wri.github.io/wri-design-systems/\n')
