name: 'PR Label Checker'
on:
  pull_request:
    branches:
      - main
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check_labels:
    name: 'Check Version Bump Labels'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'
